name: Run-Unit-Test

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build-and-test:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build AssetEditor\AssetEditor.csproj --no-restore

    - name: Run tests
      run: dotnet test Testing\E2EVerification\Test.E2EVerification.csproj --no-restore --verbosity normal