name: Run-Unit-Test

on:
  push:
    branches:
      - master
  workflow_dispatch:  # Add this line to enable manual triggering
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet dotnet build AssetEditor\AssetEditor.csproj --no-restore

    - name: Run tests
      run: dotnet test AssetEditor\Testing\E2EVerification\E2EVerification.csproj --no-restore --verbosity normal